-- NANA'S FOOD — SUPABASE V16
-- Rode este arquivo inteiro no SQL Editor do seu projeto Supabase.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admins a where a.user_id = auth.uid());
$$;

create table if not exists public.products (
  id text primary key,
  name text not null,
  description text not null default '',
  price numeric(10,2),
  image_path text not null default 'assets/doguinho.jpg',
  is_active boolean not null default true,
  is_sold_out boolean not null default false,
  is_future boolean not null default false,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.addons (
  id text primary key,
  name text not null,
  price numeric(10,2),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.condiments (
  id text primary key,
  name text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id smallint primary key default 1 check (id = 1),
  status_mode text not null default 'forced_open' check (status_mode in ('auto','forced_open','forced_closed')),
  timezone text not null default 'America/Bahia',
  max_radius_km numeric(6,2) not null default 4.5,
  default_delivery_fee numeric(10,2),
  store_cep text not null default '42809849',
  store_address text not null default '',
  store_city text not null default 'Camaçari',
  store_state text not null default 'BA',
  store_lat numeric(10,7),
  store_lng numeric(10,7),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_hours (
  day_of_week smallint primary key check (day_of_week between 0 and 6),
  is_open boolean not null default false,
  open_time time not null default '18:00',
  close_time time not null default '23:00'
);

create table if not exists public.delivery_fee_tiers (
  id bigint generated by default as identity primary key,
  up_to_km numeric(6,2) not null,
  fee numeric(10,2) not null,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

alter table public.admins enable row level security;
alter table public.products enable row level security;
alter table public.addons enable row level security;
alter table public.condiments enable row level security;
alter table public.store_settings enable row level security;
alter table public.store_hours enable row level security;
alter table public.delivery_fee_tiers enable row level security;

-- Leitura pública necessária ao site do cliente.
drop policy if exists "Public read products" on public.products;
create policy "Public read products" on public.products for select to anon, authenticated using (true);
drop policy if exists "Public read addons" on public.addons;
create policy "Public read addons" on public.addons for select to anon, authenticated using (true);
drop policy if exists "Public read condiments" on public.condiments;
create policy "Public read condiments" on public.condiments for select to anon, authenticated using (true);
drop policy if exists "Public read store settings" on public.store_settings;
create policy "Public read store settings" on public.store_settings for select to anon, authenticated using (true);
drop policy if exists "Public read store hours" on public.store_hours;
create policy "Public read store hours" on public.store_hours for select to anon, authenticated using (true);
drop policy if exists "Public read delivery tiers" on public.delivery_fee_tiers;
create policy "Public read delivery tiers" on public.delivery_fee_tiers for select to anon, authenticated using (true);

-- O administrador pode ler seu próprio cadastro.
drop policy if exists "Admin reads own access" on public.admins;
create policy "Admin reads own access" on public.admins for select to authenticated using (auth.uid() = user_id);

-- Escrita somente para administradores autorizados.
drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage addons" on public.addons;
create policy "Admins manage addons" on public.addons for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage condiments" on public.condiments;
create policy "Admins manage condiments" on public.condiments for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage settings" on public.store_settings;
create policy "Admins manage settings" on public.store_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage hours" on public.store_hours;
create policy "Admins manage hours" on public.store_hours for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admins manage delivery tiers" on public.delivery_fee_tiers;
create policy "Admins manage delivery tiers" on public.delivery_fee_tiers for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.store_settings(id,status_mode,timezone,max_radius_km,store_cep,store_city,store_state)
values(1,'forced_open','America/Bahia',4.5,'42809849','Camaçari','BA')
on conflict(id) do nothing;

insert into public.store_hours(day_of_week,is_open,open_time,close_time) values
(0,false,'18:00','23:00'),(1,false,'18:00','23:00'),(2,false,'18:00','23:00'),(3,false,'18:00','23:00'),(4,false,'18:00','23:00'),(5,false,'18:00','23:00'),(6,false,'18:00','23:00')
on conflict(day_of_week) do nothing;


-- Remove itens antigos que foram substituídos no cardápio atual.
delete from public.products where id in ('molho-verde','bacon','bacon-cheddar','frango-catupiry','catupiry');
delete from public.addons where id in ('catupiry','bacon','carne-moida','molho-verde','barbecue');

insert into public.products(id,name,description,price,image_path,is_active,is_sold_out,is_future,sort_order) values
('goob','Goob','',2.50,'assets/doguinho.jpg',true,false,false,5),
('tradicional','Hot dog simples','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha e barbecue.',5.00,'assets/doguinho.jpg',true,false,false,10),
('tradicional-duplo','Hot dog duplo','02 salsichas, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha e barbecue.',6.00,'assets/doguinho.jpg',true,false,false,20),
('bolonhesa','Hot dog bolonhesa','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, carne moída e barbecue.',6.50,'assets/doguinho.jpg',true,false,false,30),
('frango','Hot dog frango','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha e frango desfiado.',6.50,'assets/doguinho.jpg',true,false,false,40),
('cheddar','Hot dog cheddar','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, molho cheddar e barbecue.',6.50,'assets/doguinho.jpg',true,false,false,50),
('requeijao','Hot dog requeijão','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha e molho requeijão.',6.50,'assets/doguinho.jpg',true,false,false,60),
('milho','Hot dog milho','',6.50,'assets/doguinho.jpg',true,false,false,70),
('calabresa','Hot dog calabresa','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, calabresa e barbecue.',6.50,'assets/doguinho.jpg',true,false,false,80),
('frango-requeijao','Hot dog frango c/ requeijão','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, frango desfiado e requeijão.',8.00,'assets/doguinho.jpg',true,false,false,90),
('calabresa-cheddar','Hot dog calabresa c/ cheddar','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, calabresa, cheddar e barbecue.',8.00,'assets/doguinho.jpg',true,false,false,100),
('supremo','Supremo','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, carne moída, calabresa, frango, requeijão, cheddar e barbecue.',13.50,'assets/doguinho.jpg',true,false,false,110),
('mexicano','Hot dog mexicano','01 salsicha, molho, milho, queijo ralado, pimenta calabresa, vinagrete, carne moída, cheddar e Doritos.',null,'assets/doguinho.jpg',true,false,true,200),
('japones','Hot dog Japonês','01 salsicha empanada, molho tarê, cream cheese, couve crispy e pimenta biquinho.',null,'assets/doguinho.jpg',true,false,true,210),
('paulista','Hot dog Paulista','01 salsicha, molho, milho, queijo ralado, ketchup, maionese, mostarda, batata palha, barbecue e purê de batata.',null,'assets/doguinho.jpg',true,false,true,220),
('sertanejo','Hot dog sertanejo','01 salsicha, molho, carne desfiada, banana-da-terra frita, queijo coalho, batata palha e barbecue.',null,'assets/doguinho.jpg',true,false,true,230)
on conflict(id) do update set
name=excluded.name, description=excluded.description, price=excluded.price, image_path=excluded.image_path,
is_active=excluded.is_active, is_sold_out=excluded.is_sold_out, is_future=excluded.is_future,
sort_order=excluded.sort_order, updated_at=now();

insert into public.addons(id,name,price,is_active,sort_order) values
('cheddar','Cheddar',1.50,true,10),
('requeijao','Requeijão',1.50,true,20),
('calabresa','Calabresa',1.50,true,30),
('frango','Frango',1.50,true,40),
('bolonhesa','Bolonhesa',1.50,true,50),
('milho','Milho',1.00,true,60),
('salsicha','Salsicha',1.00,true,70)
on conflict(id) do update set
name=excluded.name, price=excluded.price, is_active=excluded.is_active,
sort_order=excluded.sort_order, updated_at=now();

insert into public.condiments(id,name,is_active,sort_order) values
('ketchup','Ketchup',true,10),('maionese','Maionese',true,20),('mostarda','Mostarda',true,30),('barbecue','Barbecue',true,40),('molho-verde','Molho verde',true,50)
on conflict(id) do nothing;

-- BOOTSTRAP DO PRIMEIRO ADMINISTRADOR
-- 1) Crie o usuário em Authentication > Users no painel Supabase.
-- 2) Troque o e-mail abaixo e execute SOMENTE este comando depois:
-- insert into public.admins(user_id,email)
-- select id,email from auth.users where email = 'SEU_EMAIL@EXEMPLO.COM'
-- on conflict(user_id) do update set email = excluded.email;
