const sb=window.NanasData?.client;const $=(s,sc=document)=>sc.querySelector(s);const $$=(s,sc=document)=>[...sc.querySelectorAll(s)];let cache={products:[],addons:[],condiments:[],settings:null,hours:[]};
const dayNames={0:'Domingo',1:'Segunda',2:'Terça',3:'Quarta',4:'Quinta',5:'Sexta',6:'Sábado'};const dayOrder=[1,2,3,4,5,6,0];
function show(id,on=true){$('#'+id).hidden=!on}function msg(t,err=false){$('#loginMessage').textContent=t;$('#loginMessage').className='message'+(err?' error':'')}
async function isAdmin(user){const {data,error}=await sb.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function boot(){if(!window.NanasData?.enabled){show('setupView');show('loginView',false);return}const {data:{session}}=await sb.auth.getSession();if(session&&await isAdmin(session.user))return enter(session.user);show('loginView')}
async function enter(user){show('setupView',false);show('loginView',false);show('adminView');$('#adminEmail').textContent=user.email||'';await loadAll()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();msg('Entrando...');const {data,error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)return msg(error.message,true);if(!await isAdmin(data.user)){await sb.auth.signOut();return msg('Este usuário não está autorizado como administrador.',true)}msg('');enter(data.user)});$('#logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab));$('#pageTitle').textContent={store:'Controle da loja',products:'Cardápio',extras:'Adicionais e condimentos',hours:'Horários',delivery:'Entrega'}[b.dataset.tab]}));
async function loadAll(){const [p,a,c,s,h]=await Promise.all([sb.from('products').select('*').order('sort_order'),sb.from('addons').select('*').order('sort_order'),sb.from('condiments').select('*').order('sort_order'),sb.from('store_settings').select('*').eq('id',1).single(),sb.from('store_hours').select('*').order('day_of_week')]);for(const r of[p,a,c,s,h])if(r.error)throw r.error;cache={products:p.data,addons:a.data,condiments:c.data,settings:s.data,hours:h.data};renderStore();renderProducts();renderExtras();renderHours();renderDelivery();renderStats()}
function renderStore(){$$('.mode-btn').forEach(b=>b.classList.toggle('selected',b.dataset.mode===cache.settings.status_mode));$('#storeStatusBox').textContent=cache.settings.status_mode==='forced_open'?'Loja forçada como ABERTA.':cache.settings.status_mode==='forced_closed'?'Loja forçada como FECHADA.':'Loja seguindo o horário automático.'}
$$('.mode-btn').forEach(b=>b.addEventListener('click',async()=>{const {error}=await sb.from('store_settings').update({status_mode:b.dataset.mode,updated_at:new Date().toISOString()}).eq('id',1);if(error)return alert(error.message);cache.settings.status_mode=b.dataset.mode;renderStore()}));
function renderStats(){$('#statProducts').textContent=cache.products.filter(p=>p.is_active&&!p.is_future).length;$('#statSoldOut').textContent=cache.products.filter(p=>p.is_active&&p.is_sold_out).length;$('#statRadius').textContent=`${Number(cache.settings.max_radius_km).toFixed(1).replace('.',',')} km`}
function renderProducts(){$('#productsList').innerHTML=cache.products.map(p=>`<article class="product-editor ${p.is_future?'future':''}" data-id="${p.id}"><div class="row"><label>Nome<input class="p-name" value="${escapeAttr(p.name)}"></label><label>Preço (R$)<input class="p-price" type="number" step="0.01" min="0" value="${p.price??''}"></label><button class="small-save save-product">Salvar</button></div><label>Descrição<textarea class="p-desc">${escapeHtml(p.description||'')}</textarea></label><div class="toggles"><label><input class="p-active" type="checkbox" ${p.is_active?'checked':''}> Mostrar no cardápio</label><label><input class="p-sold" type="checkbox" ${p.is_sold_out?'checked':''}> Esgotado</label>${p.is_future?'<span class="tag">EM BREVE</span>':''}</div></article>`).join('');$$('.save-product').forEach(b=>b.addEventListener('click',()=>saveProduct(b.closest('.product-editor'))))}
async function saveProduct(el){const id=el.dataset.id,payload={name:$('.p-name',el).value.trim(),description:$('.p-desc',el).value.trim(),price:$('.p-price',el).value===''?null:Number($('.p-price',el).value),is_active:$('.p-active',el).checked,is_sold_out:$('.p-sold',el).checked,updated_at:new Date().toISOString()};const {error}=await sb.from('products').update(payload).eq('id',id);if(error)return alert(error.message);await loadAll()}
function renderExtras(){$('#addonsList').innerHTML=cache.addons.map(a=>`<div class="item-editor" data-id="${a.id}"><label>Nome<input class="e-name" value="${escapeAttr(a.name)}"></label><label>Preço<input class="e-price" type="number" step="0.01" value="${a.price??''}"></label><div><label><input class="e-active" type="checkbox" ${a.is_active?'checked':''}> Ativo</label><br><button class="small-save save-addon">Salvar</button></div></div>`).join('');$('#condimentsList').innerHTML=cache.condiments.map(c=>`<div class="item-editor condiment-editor" data-id="${c.id}"><label>Nome<input class="c-name" value="${escapeAttr(c.name)}"></label><div><label><input class="c-active" type="checkbox" ${c.is_active?'checked':''}> Ativo</label><br><button class="small-save save-condiment">Salvar</button></div></div>`).join('');$$('.save-addon').forEach(b=>b.addEventListener('click',()=>saveAddon(b.closest('.item-editor'))));$$('.save-condiment').forEach(b=>b.addEventListener('click',()=>saveCondiment(b.closest('.item-editor'))))}
async function saveAddon(el){const {error}=await sb.from('addons').update({name:$('.e-name',el).value.trim(),price:$('.e-price',el).value===''?null:Number($('.e-price',el).value),is_active:$('.e-active',el).checked,updated_at:new Date().toISOString()}).eq('id',el.dataset.id);if(error)return alert(error.message);await loadAll()}
async function saveCondiment(el){const {error}=await sb.from('condiments').update({name:$('.c-name',el).value.trim(),is_active:$('.c-active',el).checked,updated_at:new Date().toISOString()}).eq('id',el.dataset.id);if(error)return alert(error.message);await loadAll()}
function renderHours(){const map=new Map(cache.hours.map(h=>[Number(h.day_of_week),h]));$('#hoursTable').innerHTML=dayOrder.map(d=>{const h=map.get(d)||{day_of_week:d,is_open:false,open_time:'18:00:00',close_time:'23:00:00'};return`<div class="hour-row" data-day="${d}"><strong>${dayNames[d]}</strong><label><input class="h-open" type="checkbox" ${h.is_open?'checked':''}> Aberto</label><label>Abre<input class="h-start" type="time" value="${String(h.open_time||'18:00').slice(0,5)}"></label><label>Fecha<input class="h-end" type="time" value="${String(h.close_time||'23:00').slice(0,5)}"></label></div>`}).join('')}
$('#saveHours').addEventListener('click',async()=>{const rows=$$('.hour-row').map(r=>({day_of_week:Number(r.dataset.day),is_open:$('.h-open',r).checked,open_time:$('.h-start',r).value+':00',close_time:$('.h-end',r).value+':00'}));const {error}=await sb.from('store_hours').upsert(rows,{onConflict:'day_of_week'});if(error)return alert(error.message);await loadAll();alert('Horários salvos.')});
function renderDelivery(){$('#adminRadius').value=cache.settings.max_radius_km??4.5;$('#adminDefaultFee').value=cache.settings.default_delivery_fee??'';$('#adminStoreCep').value=cache.settings.store_cep||'';$('#adminTimezone').value=cache.settings.timezone||'America/Bahia';$('#adminStoreAddress').value=cache.settings.store_address||'';$('#adminStoreLat').value=cache.settings.store_lat??'';$('#adminStoreLng').value=cache.settings.store_lng??''}
$('#saveDelivery').addEventListener('click',async()=>{const payload={max_radius_km:Number($('#adminRadius').value||4.5),default_delivery_fee:$('#adminDefaultFee').value===''?null:Number($('#adminDefaultFee').value),store_cep:$('#adminStoreCep').value.trim(),timezone:$('#adminTimezone').value.trim()||'America/Bahia',store_address:$('#adminStoreAddress').value.trim(),store_lat:$('#adminStoreLat').value===''?null:Number($('#adminStoreLat').value),store_lng:$('#adminStoreLng').value===''?null:Number($('#adminStoreLng').value),updated_at:new Date().toISOString()};const {error}=await sb.from('store_settings').update(payload).eq('id',1);if(error)return alert(error.message);await loadAll();alert('Configuração de entrega salva.')});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#096;')}
boot().catch(e=>{console.error(e);alert('Erro ao carregar painel: '+e.message)});